version: '3.8'

services:
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "8081:80"
    depends_on:
      - php-fpm

  php-fpm:
    container_name: app
    build:
      context: ./docker/app
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    volumes:
      - .:/var/www/html
    user: 1000:1000
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "33061:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mysql_data:



