version: '3.8'

services:
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "8081:80"
    depends_on:
      - php-fpm
    networks:
      - mynetwork

  php-fpm:
    container_name: app
    build:
      context: ./docker/app
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    volumes:
      - .:/var/www/html
    user: 1000:1000
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - mynetwork

  cron:
    build:
      context: './docker/cron'
    volumes:
      - .:/var/www/html
    user: root
    restart: on-failure
    networks:
      - mynetwork

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "33061:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

  storage:
    build:
      context: ./docker/storage
    volumes:
      - ./storage/app/public:/app
    ports:
      - "8083:80"

  storage-ftp:
    image: stilliard/pure-ftpd
    environment:
      FTP_USER_NAME: app
      FTP_USER_PASS: secret
      FTP_USER_HOME: /app
    volumes:
      - ./storage/app/public:/app
    platform: linux/amd64
    networks:
      - mynetwork

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge
