services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - .:/var/www/html
    ports:
      - "8081:80"
    depends_on:
      - php-fpm
    networks:
      - mynetwork

  php-fpm:
    container_name: app
    build:
      context: ./docker/app
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    volumes:
      - .:/var/www/html
    user: 1000:1000
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - mynetwork

  cron:
    build:
      context: './docker/cron'
    volumes:
      - .:/var/www/html
    user: root
    restart: on-failure
    networks:
      - mynetwork

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "33061:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork

  storage:
    build:
      context: ./docker/storage
    volumes:
      - ./storage/app/public:/app/public
    ports:
      - ${STORAGE_PORT:-8083}:80

  ftp-server:
    environment:
      - FTP_PASS=${STORAGE_FTP_PASSWORD:-password}
      - FTP_USER=${STORAGE_FTP_USERNAME:-app}
    image: garethflowers/ftp-server
    ports:
      - '20-21:20-21/tcp'
      - '40000-40009:40000-40009/tcp'
    volumes:
      - ./storage/app/public:${STORAGE_FTP_HOME:-/home/app}
    networks:
      - mynetwork

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mynetwork


volumes:
  mysql-data:

networks:
  mynetwork:
    driver: bridge
