POST http://localhost:8081/api/auth/register
Content-Type: application/json
Accept: application/json

{
    "first_name": "Test",
    "nick": "agent008",
    "email": "test@example1.com",
    "password": "password",
    "birth_date": "2020-02-02"
}

###
POST http://localhost:8081/api/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "test@example.com",
    "password": "password"
}

###

POST http://localhost:8081/api/auth/me
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

###

POST http://localhost:8081/api/auth/logout
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

###
